exports.SET_CURRENT_USER = "SET_CURRENT_USER"
exports.RESET_TOKEN = "RESET_TOKEN"

exports.ADD_ERROR = "ADD_ERROR";
exports.REMOVE_ERROR = "REMOVE_ERROR";

exports.SET_ACTIVE_BOOK = "SET_ACTIVE_BOOK";
exports.REMOVE_ACTIVE_BOOK = "REMOVE_ACTIVE_BOOK";